<?php
			ini_set("memory_limit","1024M");
			set_time_limit( 180000 );
			
				$export_xls_all_details ="<html><head>";
				$export_xls_all_details .="<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";
				$export_xls_all_details .="</head>";
				$export_xls_all_details .="<body>";
				foreach ($results as $result) {					
					$export_xls_all_details .="<table border='1'>";
					$export_xls_all_details .="<tr>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_order_id')."</td>";					
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_date_added')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_inv_no')."</td>";									
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_id')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_sku')."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_name')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_option')."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_model')."</td>";
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_currency')."</td>";						
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_price')."</td>";
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_quantity')."</td>";
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_prod_total')."</td>";	
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_sub_total')."</td>";				
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_shipping')."</td>";
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_tax')."</td>";							
					$export_xls_all_details .= "<td align='right' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_value')."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_shipping_method')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_payment_method')."</td>";	
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_status')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_store')."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_name'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_company'))."</td>";									
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_address_1'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_address_2'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_city'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_zone'))."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_postcode'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_billing_country'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_customer_telephone')."</td>";	
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_email')."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".$this->language->get('column_order_customer_group')."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_name'))."</td>";						
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_company'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_address_1'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_address_2'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_city'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_zone'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_postcode'))."</td>";
					$export_xls_all_details .= "<td align='left' style='background-color:#EFEFEF; font-weight:bold;'>".strip_tags($this->language->get('column_shipping_country'))."</td>";	
					$export_xls_all_details .="</tr>";
					$export_xls_all_details .="<tr>";
					$export_xls_all_details .= "<td align='left'>".$result['product_ord_idc']."</td>";					
					$export_xls_all_details .= "<td align='left'>".$result['product_order_date']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['product_inv_no']."</td>";				
					$export_xls_all_details .= "<td align='left'>".$result['product_pidc']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['product_sku']."</td>";						
					$export_xls_all_details .= "<td align='left'>".$result['product_name']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['product_option']."</td>";						
					$export_xls_all_details .= "<td align='left'>".$result['product_model']."</td>";
					$export_xls_all_details .= "<td align='right'>".$result['product_currency']."</td>";						
					$export_xls_all_details .= "<td align='right'>".$result['product_price']."</td>";
					$export_xls_all_details .= "<td align='right'>".$result['product_quantity']."</td>";
					$export_xls_all_details .= "<td align='right'>".$result['product_total']."</td>";
					$export_xls_all_details .= "<td align='right'>".$result['order_sub_total']."</td>";					
					$export_xls_all_details .= "<td align='right'>".$result['order_shipping']."</td>";
					$export_xls_all_details .= "<td align='right'>".$result['order_tax']."</td>";							
					$export_xls_all_details .= "<td align='right'>".$result['order_value']."</td>";						
					$export_xls_all_details .= "<td align='left'>".$result['order_shipping_method']."</td>";
					$export_xls_all_details .= "<td align='left'>".strip_tags($result['order_payment_method'], '<br>')."</td>";	
					$export_xls_all_details .= "<td align='left'>".$result['order_status']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['order_store']."</td>";						
					$export_xls_all_details .= "<td align='left'>".$result['billing_name']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_company']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_address_1']."</td>";					
					$export_xls_all_details .= "<td align='left'>".$result['billing_address_2']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_city']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_zone']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_postcode']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['billing_country']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['customer_telephone']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['order_email']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['order_group']."</td>";						
					$export_xls_all_details .= "<td align='left'>".$result['shipping_name']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_company']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_address_1']."</td>";					
					$export_xls_all_details .= "<td align='left'>".$result['shipping_address_2']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_city']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_zone']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_postcode']."</td>";
					$export_xls_all_details .= "<td align='left'>".$result['shipping_country']."</td>";
					$export_xls_all_details .="</tr>";					
					$export_xls_all_details .="</table>";			
				}
				$export_xls_all_details .="</body></html>";

			$filename = "sale_profit_report_all_details_".date("Y-m-d",time());
			header('Expires: 0');
			header('Cache-control: private');
			header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
			header('Content-Description: File Transfer');			
			header('Content-Type: application/vnd.ms-excel; charset=UTF-8; encoding=UTF-8');			
			header('Content-Disposition: attachment; filename='.$filename.".xls");
			header('Content-Transfer-Encoding: UTF-8');
			print $export_xls_all_details;			
			exit;
?>